# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_actor_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='Film', to='Movie.Actor'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(related_name='Film', to='Movie.Genre'),
        ),
    ]
